# spring配置
spring:
  redis:
    host: 192.168.0.88
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 192.168.0.88
    port: 5672
    username: myuser
    password: mypassword
    virtual-host: /
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
    stream:
      binders:
        myRabbit:
          type: rabbit
          environment:
            rabbitmq:
              host: 192.168.0.88
              port: 5672
              username: myuser
              password: mypassword
              virtual-host: /
      bindings: #stream绑定信道
        #如下定义 会把bean绑定在消费者operLogMq-in-0或者提供者operLogMq-out-0上
        operLogMq-out-0: #输出操作日志
          destination: topic_operLog #mq topic
          group: operLog
          binder: myRabbit #绑定器
        operLogMq-in-0:
          destination: topic_operLog
          group: operLog
          binder: myRabbit
# feign 配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      # 针对所有服务
      default:
        # feign建立连接超时时间 默认10秒
        connectTimeout: 10000
        # feign的请求处理超时时间 默认60秒
        readTimeout: 10000
        # 日志级别 NONE, BASIC, HEADERS, FULL
        loggerLevel: full
  # feign请求响应压缩配置
  compression:
    request:
      # 开启feign请求压缩配置，默认不开启
      enabled: true
      # 配置支持压缩的MIME TYPE，默认为：text/xml,application/xml,application/json
      mime-types: text/xml,application/xml,application/json
      # 触发请求数据压缩的最小Size，默认2048KB
      min-request-size: 2048
    response:
      # 开启Feign响应压缩，默认不开启
      enabled: true
      # 使用GZip解码器，默认不使用
      useGzipDecoder: false

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 86400
  # 多端不同 token 有效期 可查看 LoginHelper.loginByDevice 方法自定义
  # token最低活跃时间 (指定时间无操作就过期) 单位: 秒
  active-timeout: 1800
  # 开启内网服务调用鉴权
  check-same-token: true
  # Same-Token的有效期 (单位: 秒)(默认一天）
  # same-token-timeout: 600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token前缀
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: 1wewle30skeku3yurfewbfjsdafjk

logging:
  level:
    # 设置根logger日志级别
    root: WARN