spring:
  cloud:
    sentinel:
      # 配置Sentinel控制台地址
      transport:
        dashboard: 127.0.0.1:8081
      scg:
        fallback:
          # 指定降级处理的模式为返回响应
          mode: response
          # 响应状态码
          response-status: 200
          # 响应信息
          response-body: '{"code":429,"msg":"请求被限流"}'
    gateway:
      discovery:
        locator:
          #表示在通过服务发现（如Eureka或Consul）自动创建路由时，将服务ID转换为小写
          lowerCaseServiceId: true
          #启用基于服务发现的路由功能。当此选项开启时，Gateway能够根据注册到服务发现组件中的服务实例动态创建路由规则。
          enabled: true
      routes:
        # 认证中心
          #路由标识 要求唯一
        - id: you-auth
          #请求将被转发到名为you-auth的服务，这里的lb://前缀表明使用负载均衡器来定位目标服务实例。
          uri: lb://you-auth
          #定义了一个断言，意味着所有以/auth/开头的HTTP路径都会匹配这个路由规则。
          predicates:
            - Path=/auth/**
          #过滤器数组
          filters:
            #过滤器会从原始请求路径中移除一层路径前缀，例如将 /auth/service/path 转发到实际服务时，只传递 /service/path 给目标服务。
            - StripPrefix=1
        # 系统模块
        - id: you-system
          uri: lb://you-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
#权限配置
auth:
  ignore:
    # 放行白名单
    whiteList:
      - /auth/verifyCode
      - /auth/logout
      - /auth/login

# 安全配置
security:
  # 防止XSS攻击
  xss:
    # 放行名单
    excludeUrls: