spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: you-auth
          uri: lb://you-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: you-system
          uri: lb://you-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
#权限配置
auth:
  ignore:
    # 放行白名单
    whiteList:
      - /auth/verifyCode
      - /auth/logout

# 安全配置
security:
  # 防止XSS攻击
  xss:
    # 放行名单
    excludeUrls: