# 使用 ElasticSearch 官方提供的基础镜像
FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.2

# 配置环境变量
ENV discovery.type=single-node

# 暴露默认的端口
EXPOSE 9200 9300

# 将默认的启动命令设置为 Elasticsearch
CMD ["elasticsearch"]